from BackEnd.app.models.users import Users
from BackEnd.app.models.departments import Departments
from BackEnd.app.models.equipment import Equipment
from BackEnd.app.models.tickets import Tickets
from BackEnd.app.models.history_tickets import TicketHistory
from BackEnd.app.models.ticket_ratings import TicketRating
from BackEnd.app.models.notification_reads import NotificationRead
from BackEnd.app.models.audit_log import AuditLog
from BackEnd.app.models.categories import Categories
